import React, { useState, useEffect } from 'react';
import Artists from './Artists';
import { useSession } from 'next-auth/react';
import { ArtistType } from '../types';
import Button from '@mui/material/Button';
import Snackbar from '@mui/material/Snackbar';
import MuiAlert, { AlertProps } from '@mui/material/Alert';

const Alert = React.forwardRef<HTMLDivElement, AlertProps>(function Alert(
  props,
  ref
) {
  return <MuiAlert elevation={6} ref={ref} variant="filled" {...props} />;
});

const getAccessToken = async () => {
  const SPOTIFY_CLIENT_ID = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID;
  const SPOTIFY_CLIENT_SECRET = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET;
  const SPOTIFY_REFRESH_TOKEN = process.env.NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN;
  const BASIC = Buffer.from(
    `${SPOTIFY_CLIENT_ID}:${SPOTIFY_CLIENT_SECRET}`
  ).toString('base64');
  const TOKEN_ENDPOINT = `https://accounts.spotify.com/api/token?`;
  const TOKEN_URL =
    TOKEN_ENDPOINT +
    // @ts-expect-error
    new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: SPOTIFY_REFRESH_TOKEN,
    });
  const response = await fetch(TOKEN_URL, {
    headers: {
      Authorization: `Basic ${BASIC}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    method: 'POST',
  });
  return response.json();
};

const getTopTracksForArtist = async (artistId: string) => {
  const { access_token } = await getAccessToken();
  const response = await fetch(
    `https://api.spotify.com/v1/artists/${artistId}/top-tracks?market=US&limit=3`,
    {
      headers: {
        Authorization: `Bearer ${access_token}`,
      },
    }
  );
  const { tracks } = await response.json();
  // TODO: Allow users to pick how many songs they want per artist
  return tracks.splice(0, 5);
};

const createPlaylistForUser = async (
  userId: string,
  setPlaylistId: Function
) => {
  const url = `https://api.spotify.com/v1/users/${userId}/playlists`;
  const payload = {
    name: 'Concert Poster to Playlist',
    description: 'A playlist generated by uploading a concert poster image',
    public: true,
  };
  const { access_token } = await getAccessToken();

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${access_token}`,
    },
    body: JSON.stringify(payload),
  });
  const data = await response.json();
  if (data.id) {
    setPlaylistId(data.id);
  }
  console.log(`Playlist successfully created: `, data);
  return data.id;
};

const addTracksToPlaylist = async (playlistId: string, uris: string[]) => {
  const url = `https://api.spotify.com/v1/playlists/${playlistId}/tracks`;
  const payload = {
    uris,
  };
  const { access_token } = await getAccessToken();

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${access_token}`,
    },
    body: JSON.stringify(payload),
  });
  const data = await response.json();
  console.log(`Successfully added tracks to playlist ${playlistId}: `, data);
  return data;
};

const Spotify = (props: any) => {
  const { artistListObject, setArtistListObject, isLoading, setIsLoading } =
    props;
  const { data: session } = useSession();
  const [tracks, setTracks] = useState([]);
  const [trackUris, setTrackUris] = useState([]);
  const [playlistId, setPlaylistId] = useState('');
  const [open, setOpen] = React.useState(false);

  useEffect(() => {
    async function getTopTracksForSelectedArtists() {
      const filteredList = artistListObject.filter(
        (artist: any) => artist.selected === true
      );
      const promises = filteredList.map((artist: ArtistType) =>
        getTopTracksForArtist(artist.id)
      );
      const topTracks = await Promise.all(promises);
      // TODO: Find work around to allow more than 100 songs to be added to a playlist
      const flattenedList: any = topTracks.flat().splice(0, 100);
      console.log(
        `Got back top tracks for all selected artists: `,
        flattenedList
      );
      setTracks(flattenedList);
      const trackUris = flattenedList.map((track: any) => track.uri);
      setTrackUris(trackUris);
    }

    getTopTracksForSelectedArtists();
  }, [artistListObject]);

  const handleCreate = async () => {
    // @ts-expect-error
    const userId = session?.token?.sub;
    const playlistId = await createPlaylistForUser(userId, setPlaylistId);
    // TODO: Find a way to add more than 100 tracks to a playlist
    await addTracksToPlaylist(playlistId, trackUris);
    setOpen(true);
  };

  const handleSelectAll = () => {
    setArtistListObject((prevList: any) => {
      const newList = prevList.slice().map((item: any) => {
        item.selected = true;
        return item;
      });
      return newList;
    });
  };

  const handleUnselectAll = () => {
    setArtistListObject((prevList: any) => {
      const newList = prevList.slice().map((item: any) => {
        item.selected = false;
        return item;
      });
      return newList;
    });
  };

  const handleClose = (
    event?: React.SyntheticEvent | Event,
    reason?: string
  ) => {
    if (reason === 'clickaway') {
      return;
    }
    setOpen(false);
  };

  if (artistListObject.length === 0) return null;
  return (
    <>
      <Snackbar open={open} autoHideDuration={10000} onClose={handleClose}>
        <Alert onClose={handleClose} severity="success" sx={{ width: '100%' }}>
          Successfully create new playlist! Open your Spotify app or view it{' '}
          <a
            target="_blank"
            href="https://open.spotify.com/playlist/1DEpVnMMxPHL60LwxCeaHg"
          >
            here
          </a>
        </Alert>
      </Snackbar>
      {!isLoading && (
        <>
          <Artists
            artists={artistListObject}
            handleSelectAll={handleSelectAll}
            handleUnselectAll={handleUnselectAll}
            setArtistListObject={setArtistListObject}
          />
          <Button
            className="create-btn"
            variant="contained"
            color="success"
            onClick={handleCreate}
          >
            Create new playlist with selected artists
          </Button>
        </>
      )}
    </>
  );
};

export default Spotify;
